services:
  myapp:
    image: dataregister:1.0.0
    container_name: dataregister-container
    ports:
      - "8081:8081"
    environment:
      - datasource.url={url}
      - datasource.username={name}
      - datasource.password={pass}
      - spring.profiles.active=prod
    networks:
      - myapp-network
    restart: always

networks:
  myapp-network:
    driver: bridge