services:
  myapp:
    image: dataregister:1.0.0
    container_name: dataregister-container
    ports:
      - "8081:8081"
    environment:
      - datasource.url=URL
      - datasource.username=USERNAME
      - datasource.password=PASSWORD
      - spring.profiles.active=prod
    networks:
      - myapp-network
    restart: always

networks:
  myapp-network:
    driver: bridge