services:
  myapp:
    image: dataregister:1.0.0
    container_name: dataregister-container
    ports:
      - "8081:8081"
    environment:
      - datasource.url=jdbc:postgresql://dpg-cv9g4bhu0jms73ejq2l0-a.oregon-postgres.render.com:5432/hdb_postgresql_instance
      - datasource.username=hdb_postgresql_instance_user
      - datasource.password=SDzUuxEinar0SwGj5dBT0jaNgptmxZzq
      - spring.profiles.active=prod
    networks:
      - myapp-network
    restart: always

networks:
  myapp-network:
    driver: bridge